### ISSUE TITLE
Wrong calculationg bytes in row for bitmap.

### ISSUE THREAD

**Issue by Reddds** [FREEWING-JP/RaspberryPi_KeDei_35_lcd_v50#1]
If width of bitmap * 3 MOD 4 == 0 then bytes in row greater then necessary on 4.

Right calculation:
`uint8_t d = (iwidth * 3) % 4;
rowbytes = (iwidth * 3);
if(d > 0)
{
	rowbytes += 4 - d;
}`

**Comment by FREEWING-JP** [comment]
Thank you your support .
I will fix it .

**Comment by FREEWING-JP** [comment]
Thank you your support .
Merged .
